--
--  Database: Contoso 100M
--  CPU: AMD Ryzen 9 7900X 12-Core Processor 4.70 GHz
--
EVALUATE
{
    SUMX (
        'Product', 
        -- Expand [Sales Amount]
        CALCULATE (
            SUMX ( 
                Sales, 
                Sales[Quantity] * Sales[Net Price] 
            )
        )
        -- End of [Sales Amount]
    )
}
