--
--  Database: Contoso 100M
--  CPU: AMD Ryzen 9 7900X 12-Core Processor 4.70 GHz
--
EVALUATE
SUMMARIZECOLUMNS (
    Customer[Continent],
    "# Orders 1", DISTINCTCOUNT ( Sales[Order Number] ),
    "# Orders 2", COUNTROWS ( Orders )
)
