--
--  Database: Contoso 100M
--  CPU: AMD Ryzen 9 7900X 12-Core Processor 4.70 GHz
--
EVALUATE
SUMMARIZECOLUMNS (
    'Date'[Year Month Number],
    "# Stores", 
    CALCULATE ( 
        SUMX ( DISTINCT ( Sales[StoreKey] ), 1 ),
        DATESYTD ( 'Date'[Date] )
    )
)