--
--  Database: Contoso 100M
--  CPU: AMD Ryzen 9 7900X 12-Core Processor 4.70 GHz
--
EVALUATE
SUMMARIZECOLUMNS (
    'Date'[Date],
    Customer[Country],
    'Product'[Color],
    "# Products", SUMX ( DISTINCT ( Sales[ProductKey] ), 1 )
)