--
--  Database: Contoso 1M
--  CPU: AMD Ryzen 9 7900X 12-Core Processor 4.70 GHz
--
EVALUATE
VAR AllSales = [Sales Amount] * 0.10
RETURN
    FILTER (
        ADDCOLUMNS (
            SUMMARIZE ( Sales, Product[Brand] ),
            "Sales",
                VAR SalesAmount = [Sales Amount]
                RETURN
                    IF ( SalesAmount >= AllSales, SalesAmount )
        ),
        NOT ( ISBLANK ( [Sales] ) )
    ) 
