--
--  Database: Contoso 100M
--  CPU: AMD Ryzen 9 7900X 12-Core Processor 4.70 GHz
--
EVALUATE
SUMMARIZECOLUMNS (
    'Product'[Brand],
    "# Products",  DISTINCTCOUNT ( Sales[ProductKey] ),
    "# Customers", DISTINCTCOUNT ( Sales[CustomerKey] ),
    "# Orders",    DISTINCTCOUNT ( Sales[Order Number] )
)
