--
--  Database: Contoso 100M
--  CPU: AMD Ryzen 9 7900X 12-Core Processor 4.70 GHz
--
EVALUATE
{
    SUMX (
        SUMMARIZE ( Sales, Customer[CustomerKey], Store[StoreKey] ),
        [Sales Amount]
    )
}
