--
--  Database: Contoso 100M
--  CPU: AMD Ryzen 9 7900X 12-Core Processor 4.70 GHz
--
EVALUATE
SUMMARIZECOLUMNS (
    'Date'[Year Month Number],
    'Product'[Color],  
    "# Products", 
        VAR LastVisibleDate = MAX ( 'Date'[Date] )
        RETURN 
            CALCULATE ( 
                SUMX ( DISTINCT ( Sales[ProductKey] ), 1 ),
                'Date'[Date] <= LastVisibleDate
            )
)