--
--  Database: Contoso 100M
--  CPU: AMD Ryzen 9 7900X 12-Core Processor 4.70 GHz
--
EVALUATE
{
    SUMX (
        SUMMARIZE ( Sales, Sales[CustomerKey], Sales[StoreKey] ),
        [Sales Amount]
    )
}
