--
--  Database: Contoso 100M
--  CPU:      AMD Ryzen Threadripper 3970X 32-Core Processor 3.72 GHz
--
EVALUATE
SUMMARIZECOLUMNS (
    'Product'[Product Name],
    "Last price",
        CALCULATE (
            VAR LastOrderDate =
                MAX ( Sales[Order Date] )
            VAR Result =
                CALCULATE ( AVERAGE ( Sales[Net Price] ), Sales[Order Date] = LastOrderDate )
            RETURN
                Result
        )
)
ORDER BY 'Product'[Product Name]
