--
--  Database: Contoso 100Mx10
--  CPU: AMD Ryzen 9 7900X 12-Core Processor 4.70 GHz
--
EVALUATE
SUMMARIZECOLUMNS (
    'Product'[Brand],
    "Test",
        SUMX (
            Sales,
            Sales[Quantity] * Sales[Net Price]
        )
)
