--
--  Database: Contoso 100M
--  CPU: AMD Ryzen 9 7900X 12-Core Processor 4.70 GHz
--
EVALUATE
SUMMARIZECOLUMNS (
    Customer[Continent],
    "Amt",
        CALCULATE (
            DIVIDE (
                SUMX ( Sales, Sales[Quantity] * Sales[Net Price] ),
                COUNTROWS ( 'Product' )
            ),
            CROSSFILTER ( Sales[ProductKey], 'Product'[ProductKey], BOTH )
        )
)
