--
--  Database: Contoso 100M
--  CPU: AMD Ryzen 9 7900X 12-Core Processor 4.70 GHz
--
EVALUATE
UNION ( 
    ADDCOLUMNS ( 
        VALUES ( Product[Brand] ),
        "Dc1", CALCULATE ( DISTINCTCOUNT ( Sales[StoreKey] ) )
    ),
    ADDCOLUMNS ( 
        VALUES ( Product[Brand] ),
        "Dc2", CALCULATE ( DISTINCTCOUNT ( Sales[StoreKey] ) )
    )
)