--
--  Database: Contoso 100Mx10
--  CPU: AMD Ryzen 9 7900X 12-Core Processor 4.70 GHz
--
EVALUATE
SUMMARIZECOLUMNS (
    'Product'[Brand],
    "Discount if greater than 3",
        SUMX (
            Sales,
            Sales[Quantity] * Sales[Net Price] 
                * ( 8 + 2 * ( Sales[Quantity] <= 3 ) )
        ) / 10
)