--
--  Database: Contoso 100M
--  CPU: AMD Ryzen 9 7900X 12-Core Processor 4.70 GHz
--
DEFINE
    COLUMN 'Product'[Margin %] = 
        ( 'Product'[Unit Price] - 'Product'[Unit Cost] ) / 'Product'[Unit Price]

EVALUATE
SUMMARIZECOLUMNS (
    'Product'[Brand],
    "Avg Margin %", AVERAGEX ( Sales, RELATED ( 'Product'[Margin %] ) )
)
