--
--  Database: Contoso 100M
--  CPU: AMD Ryzen 9 7900X 12-Core Processor 4.70 GHz
-- 
-- Use the Scenario table created in the previous demo
-- We reuse the measure with a SWITCH over Scenario (string)
DEFINE
    MEASURE Sales[Amount Corrected Hardcoded] =
        [Sales Amount] * 
        SWITCH (
            SELECTEDVALUE ( Scenario[Scenario] ),
            "Low", 0.9,
            "Medium", 1.0,
            "High", 1.1,
            1
        )

EVALUATE
SUMMARIZECOLUMNS ( 
    Scenario[Scenario], 
    Customer[City],
    TREATAS ( { "Low", "Medium" }, Scenario[Scenario] ),
    "Amount Corrected", [Amount Corrected Hardcoded] 
)
