--
--  Database: Contoso 100M
--  CPU: AMD Ryzen 9 7900X 12-Core Processor 4.70 GHz
-- 

--  Create the following calculated table
Scenario = 
    SELECTCOLUMNS (
        {
            ( "Low",    0.9, 1 ),
            ( "Medium", 1.0, 2 ),
            ( "High",   1.1, 3 )
        },
        "Scenario", [Value1],
        "Multiplier", [Value2],
        "Sort Order", [Value3]
    )

-- Then evaluate this query in DAX Studio
DEFINE
    MEASURE Sales[Amount Corrected Data Driven] =
        [Sales Amount] * SELECTEDVALUE ( Scenario[Multiplier] )

    MEASURE Sales[Amount Corrected Hardcoded] =
        [Sales Amount] * 
        SWITCH (
            SELECTEDVALUE ( Scenario[Scenario] ),
            "Low", 0.9,
            "Medium", 1.0,
            "High", 1.1,
            1
        )

EVALUATE
SUMMARIZECOLUMNS ( 
    Scenario[Scenario], 
    "Amount Corrected", [Amount Corrected Hardcoded] 
)
