--
--  Database: Contoso 100M
--  CPU: AMD Ryzen 9 7900X 12-Core Processor 4.70 GHz
--
EVALUATE
ADDCOLUMNS ( 
    VALUES ( 'Product'[Color] ),
    "Quantity", CALCULATE ( SUMX ( Sales, Sales[Quantity] ) )
)
