--
--  Database: Contoso 100Mx10 DQ
--  CPU: AMD Ryzen 9 7900X 12-Core Processor 4.70 GHz
--
EVALUATE
SUMMARIZECOLUMNS (
    'Product'[Brand],
    "Sales Filtered",
        CALCULATE (
            [Sales Amount],
            KEEPFILTERS ( CONTAINSSTRING ( 'Product'[Brand], "W" ) )
        )
)
