--
--  Database: Contoso 100Mx10 DQ
--  CPU: AMD Ryzen 9 7900X 12-Core Processor 4.70 GHz
--
--  Execute the query with different settings in the Tabular model
--  Make sure the Compatibility Level is >= 1569
--  Set Model\MaxParallelismPerQuery to 1 for sequential execution
--  Set Model\MaxParallelismPerQuery to 0 for max parallelism
--
EVALUATE
SUMMARIZECOLUMNS (
    'Product'[Brand],
    "Fabrikam",
        CALCULATE (
            DISTINCTCOUNT ( Sales[CustomerKey] ),
            'Product'[Brand] = "Fabrikam"
        ),
    "Contoso and Litware",
        CALCULATE (
            DISTINCTCOUNT ( Sales[CustomerKey] ),
            'Product'[Brand] IN { "Contoso", "Litware" } ),
    "Red",
        CALCULATE (
            DISTINCTCOUNT ( Sales[CustomerKey] ),
            'Product'[Color] = "Red"
        )
)
