--
--  Database: Contoso 100Mx10 DQ
--  CPU: AMD Ryzen 9 7900X 12-Core Processor 4.70 GHz
--
--  Execute the query with max parallelism
--  Model\MaxParallelismPerQuery = 0 (it is the default)
--
EVALUATE
SUMMARIZECOLUMNS (
    'Product'[Brand],
    "IF Example",
        VAR SalesAmount = [Sales Amount]
        VAR Margin = [Margin]
        RETURN
        IF (
            SalesAmount > 1E3,
            Margin,
            SalesAmount
        )
)
