--
--  Database: Contoso 100M
--  CPU: AMD Ryzen 9 7900X 12-Core Processor 4.70 GHz
--

-- 
-- This query uses Sales-Product relationship
--
EVALUATE
{
    CALCULATE (
        COUNTROWS ( Sales ),
        'Product'[Brand] = "Contoso"
    )
}


-- Corresponding code if execution was checking row-by-row
EVALUATE
{
    SUMX (
        Sales,
        IF ( RELATED ( 'Product'[Brand] ) = "Contoso", 1, 0 )
    )
}

-- Real execution is different (see diagram)