--
--  Database: Contoso 100M
--  CPU: AMD Ryzen 9 7900X 12-Core Processor 4.70 GHz
--
EVALUATE
SUMMARIZECOLUMNS (
    'Product'[Product Name],
    "Last price",
        CALCULATE (
            AVERAGE ( Sales[Net Price] ),
            LASTDATE ( Sales[Order Date] )
        )
)
ORDER BY 'Product'[Product Name]
