--
--  Database: Contoso 100M
--  CPU: AMD Ryzen Threadripper 3970X 32-Core Processor 3.72 GHz
--
EVALUATE
SUMMARIZECOLUMNS (
    'Product'[Brand],
    "Sales",
        SUMX (
            CorrectionFactor,
            [Sales Amount] * CorrectionFactor[Correction Factor]
        )
)
