--
--  Database: Contoso 100M
--  CPU: AMD Ryzen Threadripper 3970X 32-Core Processor 3.72 GHz
--
EVALUATE
SUMMARIZECOLUMNS (
    'Product'[Brand],
    "Sales",
        SUMX (
            Sales,
            Sales[Quantity] * Sales[Net Price]
                * RELATED ( CorrectionFactor[Correction Factor] )
        )
)

