--
--  Database: Contoso 100M
--  CPU: AMD Ryzen Threadripper 3970X 32-Core Processor 3.72 GHz
--

-------------------------------------
-- Calculated column in Product table
-------------------------------------
Product Level = 
VAR AverageSales =
    AVERAGEX (
        'Product',
        CALCULATE ( [Sales Amount], ALLEXCEPT ( 'Product', 'Product'[ProductKey] ) )
    )
VAR ProductSales = 
    CALCULATE ( 
        [Sales Amount], 
        ALLEXCEPT ( 'Product', 'Product'[ProductKey] ) 
    )
VAR Result = IF ( ProductSales >= AverageSales, "Top Seller", "Regular Seller" )
RETURN Result
