--
--  Database: Composite model
--  CPU: AMD Ryzen Threadripper 3970X 32-Core Processor 3.72 GHz
--
EVALUATE
SUMMARIZECOLUMNS (
    'Product'[Brand],
    "Sales",
        VAR SalesByYear =
            SELECTCOLUMNS (
                VALUES ( 'Date'[Year] ),
                "@Year", 'Date'[Year] + 0,
                "@Sales Amount", [Sales Amount]
            )
        VAR Corrections =
            SELECTCOLUMNS (
                CorrectionFactor,
                "@Year", CorrectionFactor[Year] + 0,
                "@Correction Factor", CorrectionFactor[Correction Factor]
            )
        VAR SalesWithFactor =
            NATURALINNERJOIN ( SalesByYear, Corrections )
        VAR Result =
            SUMX ( SalesWithFactor, [@Sales Amount] * [@Correction Factor] )
        RETURN
            Result
)
