--
--  Database: Contoso 100M
--  CPU: AMD Ryzen 9 7900X 12-Core Processor 4.70 GHz
--
DEFINE
    MEASURE Sales[Total Discount] = 
        SUMX ( Sales, Sales[Unit Price] - Sales[Net Price] ) 
EVALUATE
{
    MAXX (
        SUMMARIZECOLUMNS (
            Customer[CustomerKey],
            "@TD", [Total Discount]
        ),
        [@TD]
    )
}
