--
--  Database: Contoso 100M x 10 on Analysis Services
--  CPU:      AMD Ryzen Threadripper 3970X 32-Core Processor 3.72 GHz
--
DEFINE
    MEASURE Sales[Sales of best products] =
        CALCULATE ( 
            [Sales Amount],
            FILTER ( 
                'Product',
                [Sales Amount] >= AVERAGEX ( 'Product', [Sales Amount] )
            )
        )

EVALUATE
SUMMARIZECOLUMNS (
    Customer[Country],
    "Sales of best products", [Sales of best products]
)