--
--  Database: Contoso 100M.PBIX
--  CPU:      AMD Ryzen Threadripper 3970X 32-Core Processor 3.72 GHz
--
DEFINE
    MEASURE Sales[# Customers] =
        DISTINCTCOUNT ( Sales[CustomerKey] )
    MEASURE Sales[Growth] =
        IF (
            AND (
                [# Customers] > 0,
                CALCULATE ( [# Customers], SAMEPERIODLASTYEAR ( 'Date'[Date] ) ) > 0
            ),
            DIVIDE (
                [# Customers] - CALCULATE ( [# Customers], SAMEPERIODLASTYEAR ( 'Date'[Date] ) ),
                CALCULATE ( [# Customers], SAMEPERIODLASTYEAR ( 'Date'[Date] ) )
            )
        )

EVALUATE
SUMMARIZECOLUMNS ( 'Date'[Year], "Growth %", [Growth] )
