--
--  Database: Contoso 100M
--  CPU: AMD Ryzen 9 7900X 12-Core Processor 4.70 GHz
--
DEFINE
    MEASURE Sales[Sales RT] =
        VAR CurrentSales = [Sales Amount] 
        VAR ProductsWithSales = 
            ADDCOLUMNS ( 
                ALL ( 'Product'[ProductKey] ),
                "@Sales Amount", [Sales Amount] 
            )
        VAR ProductsWithMoreSales =
            FILTER (
                ProductsWithSales,
                [@Sales Amount] >= CurrentSales
            )
        VAR Result =
            SUMX (
                ProductsWithMoreSales,
                [@Sales Amount]
            )
        RETURN
            Result
EVALUATE
ADDCOLUMNS (
    ALL ( 'Product'[ProductKey] ),
    "Sales RT", [Sales RT]
)

