--
--  Database: Contoso 100M x 10 on AS Tabular
--  CPU:      AMD Ryzen Threadripper 3970X 32-Core Processor 3.72 GHz
--
DEFINE
    MEASURE Sales[Test] =
        CALCULATE (
            [Sales Amount],
            TREATAS ( 
                GENERATESERIES ( 1, 1000, 0.5 ), 
                'Product'[Unit Cost] 
            )
        )

EVALUATE
    SUMMARIZECOLUMNS ( 
        "Amount", [Test] 
    )

