--
--  Database: Contoso 100M x 10 on AS Tabular
--  CPU:      AMD Ryzen Threadripper 3970X 32-Core Processor 3.72 GHz
--
DEFINE
    MEASURE Sales[Test] =
        CALCULATE (
            [Sales Amount],
            KEEPFILTERS ( Sales[Quantity] = 2 || Sales[Net Price] >= 20 )
        )

EVALUATE
SUMMARIZECOLUMNS (
    'Product'[Color],
    "Test", [Test]
)


