--
--  Database: Contoso 100M x 10 on AS Tabular
--  CPU:      AMD Ryzen Threadripper 3970X 32-Core Processor 3.72 GHz
--
DEFINE
    MEASURE Sales[Test] =
        CALCULATE (
            [Sales Amount],
            'Date'[Year] >= 2015
        )

EVALUATE
    SUMMARIZECOLUMNS (
        "Amount", [Test]
    )
