--
--  Database: Contoso 100M x 10 on AS Tabular
--  CPU:      AMD Ryzen Threadripper 3970X 32-Core Processor 3.72 GHz
--
DEFINE
    MEASURE Sales[Test] =
        CALCULATE (
            [Sales Amount],
            FILTER ( 
                Customer,
                OR (
                    AND ( 
                        Customer[Country] >= "Italy",
                        Customer[Country] <= "Italy"
                    ),
                    AND ( 
                        Customer[Continent] >= "North America",
                        Customer[Continent] <= "North America"
                    )
                )
            )
        )

EVALUATE
SUMMARIZECOLUMNS ( 
    "Amount", [Test] 
)
