--
--  Database: Contoso 100M x 10 on AS Tabular
--  CPU:      AMD Ryzen Threadripper 3970X 32-Core Processor 3.72 GHz
--
EVALUATE
{
    COUNTROWS (
        FILTER (
            Sales,
            RELATED ( Customer[CustomerKey] ) >= 1
                && RELATED ( 'Product'[ProductKey] ) >= 1
                && RELATED ( Store[StoreKey] ) >= 1
        )
    )
}
