--
--  Database: Contoso 100M x 10 on AS Tabular
--  CPU:      AMD Ryzen Threadripper 3970X 32-Core Processor 3.72 GHz
--
EVALUATE
{
    CALCULATE (
        COUNTROWS ( Sales ),
        Customer[CustomerKey] >= 1,
        'Product'[ProductKey] >= 1,
        Store[StoreKey] >= 1
    )
}
