--
--  Database: Contoso 100M (includes Orders calculated table)
--            or use "S03.M06.L09 - Contoso 100M + Order Number.PBIT" template
--  CPU:      AMD Ryzen Threadripper 3970X 32-Core Processor 3.72 GHz
--
DEFINE MEASURE Sales[Open Orders] = 
    VAR StartDate = MIN ( 'Date'[Date] )
    VAR EndDate = MAX ( 'Date'[Date] )
    VAR Result = 
    CALCULATE ( 
        COUNTROWS( Orders ),
        Orders[Order Date] <= EndDate,
        Orders[Delivery Date] >= StartDate
    )
    RETURN 
        Result
EVALUATE
    SUMMARIZECOLUMNS (
        'Date'[Date],
        TREATAS ( { 2015 }, 'Date'[Year] ),
        "Open Orders",  [Open Orders]
    )
ORDER BY [Date]

