--
--  Database: Contoso 100M
--  CPU: AMD Ryzen 9 7900X 12-Core Processor 4.70 GHz
--
DEFINE
    MEASURE Sales[Total Discount] =
        SUMX (
            Customer,
            [Sales Amount] * Customer[Discount %]
        )

EVALUATE
SUMMARIZECOLUMNS (
    'Date'[Year],
    "Total Discount", [Total Discount]
)
ORDER BY 'Date'[Year]
