--
--  Database: Contoso 100M
--  CPU: AMD Ryzen 9 7900X 12-Core Processor 4.70 GHz
--
DEFINE
    MEASURE Sales[Sales Contoso] =
        CALCULATE ( [Sales Amount], KEEPFILTERS ( 'Product'[Brand] = "Contoso" ) )
    MEASURE Sales[Sales Fabrikam] =
        CALCULATE ( [Sales Amount], KEEPFILTERS ( 'Product'[Brand] = "Fabrikam" ) )
    MEASURE Sales[Sales Litware] =
        CALCULATE ( [Sales Amount], KEEPFILTERS ( 'Product'[Brand] = "Litware" ) )
    MEASURE Sales[Sales Fancy Brands] = 
        [Sales Contoso] + [Sales Fabrikam] + [Sales Litware]

EVALUATE
SUMMARIZECOLUMNS (
    'Product'[Color],
    "Sales Fancy Brands", [Sales Fancy Brands]
)
