--
--  Database: Contoso 100M
--  CPU: AMD Ryzen 9 7900X 12-Core Processor 4.70 GHz
--
DEFINE
    MEASURE Sales[Sales Brand Corrected] =
        VAR SalesAmount = [Sales Amount]
        VAR Factor = 
            SWITCH (
                SELECTEDVALUE ( 'Product'[Brand] ),
                "Contoso", 1.01,
                "Fabrikam", 1.02,
                "Litware", 1.03,
                1
            )
        VAR Result = SalesAmount * Factor
        RETURN
            Result
    MEASURE Sales[Sales Amount Corrected] =
        SUMX ( 
            VALUES ( 'Product'[Brand] ), 
            [Sales Brand Corrected] 
        )

EVALUATE
SUMMARIZECOLUMNS (
    'Product'[Color],
    "Sales Amount", [Sales Amount],
    "Sales Amount Corrected", [Sales Amount Corrected]
)
