--
--  Database: Contoso 100M
--  CPU: AMD Ryzen 9 7900X 12-Core Processor 4.70 GHz
--
DEFINE
    MEASURE Sales[Running Total] =
        SUMX (
            WINDOW (
                0, ABS,
                0, REL,
                ORDERBY ( 'Date'[Date] )
            ),
            [Sales Amount]
        )
EVALUATE
SUMMARIZECOLUMNS (
    'Date'[Date],
    "Running Total", [Running Total]
)
