--
--  Database: Contoso 100M
--  CPU: AMD Ryzen 9 7900X 12-Core Processor 4.70 GHz
--
DEFINE
    MEASURE Sales[Running Total] =
        CALCULATE (
            [Sales Amount],
            DATESBETWEEN (
                'Date'[Date],
                BLANK (),
                MAX ( 'Date'[Date] )
            )
        )
EVALUATE
SUMMARIZECOLUMNS (
    'Date'[Date],
    "Running Total", [Running Total]
)
