--
--  Database: Contoso 100Mx10 DQ
--  CPU:      AMD Ryzen Threadripper 3970X 32-Core Processor 3.72 GHz
--

-------------------------------------------------------
-- Calculated Column: 'Currency Exchange'[CurrencyDate]
-------------------------------------------------------
COLUMN 'Currency Exchange'[CurrencyDate] = 
     'Currency Exchange'[FromCurrency] & "-" 
   & 'Currency Exchange'[ToCurrency] & "-" 
   & 'Currency Exchange'[Date]

-------------------------------------------
-- Calculated Column: 'Sales'[CurrencyDate]
-------------------------------------------
COLUMN Sales[CurrencyDate] = Sales[Currency Code] & "-USD-" & Sales[Order Date]

-------------
-- Test query
-------------
EVALUATE
SUMMARIZECOLUMNS (
    Sales[Currency Code],
    "Original Currency",
        SUMX (
            Sales,
            Sales[Quantity] * Sales[Net Price] / RELATED ( 'Currency Exchange'[Exchange] )
        )
)
