--
--  Database: Contoso 100Mx10 DQ
--  CPU:      AMD Ryzen Threadripper 3970X 32-Core Processor 3.72 GHz
--
EVALUATE
SUMMARIZECOLUMNS (
    'Date'[Year],
    FILTER (
        ALL ( 'Sales'[Order Date] ),
        Sales[Order Date] >= DATE ( 2020, 1, 1 )
    ),
    "Sales", [Sales Amount]
)
ORDER BY 'Date'[Year]
