--
--  Database: Contoso 100Mx10 DQ
--  CPU:      AMD Ryzen Threadripper 3970X 32-Core Processor 3.72 GHz
--
EVALUATE
SUMMARIZECOLUMNS (
    Customer[Country],
    'Date'[Date],
    "# Products", DISTINCTCOUNT( Sales[ProductKey] )
)
