--
--  Database: Contoso 100Mx10 DQ
--  CPU: AMD Ryzen 9 7900X 12-Core Processor 4.70 GHz
--
--  Set the Product table as Dual 
--  and AggregatedSales to Import
--  before executing the query
--
--
--  IMPORTANT: remove ProductKey aggregation before the demo
-- 
--  Execute the query before and after adding the
--  GroupBy summarization by Sales[ProductKey]
--  in the AggregatedSales aggregation
--
EVALUATE
SUMMARIZECOLUMNS (
    'Date'[Year],
    Product[Brand],
    "Number of products", DISTINCTCOUNT ( Sales[ProductKey] )
)