--
--  Database: Contoso 100Mx10 DQ
--  CPU: AMD Ryzen 9 7900X 12-Core Processor 4.70 GHz
--
--
DEFINE
    MEASURE Sales[Sales Amount] =
        VAR SalesVP = SUMX ( 'Sales Vp', 'Sales Vp'[Quantity] * 'Sales Vp'[Net Price] )
        VAR SalesDQ = SUMX ( Sales, Sales[Quantity] * Sales[Net Price] )
        RETURN
        IF.EAGER (
            ISFILTERED ( Sales[Order Number] ), SalesDq, SalesVp
        )

EVALUATE
SUMMARIZECOLUMNS (
    'Date'[Year],
    Customer[Continent],
    Customer[Country],
    "Sales", [Sales Amount]
)
