--
--  Database: Contoso 100Mx10 DQ
--  CPU: AMD Ryzen 9 7900X 12-Core Processor 4.70 GHz
--
--  Set the Product table as Dual 
--  and AggregatedSales to Import
--  before executing the query
--
--  IMPORTANT: remove the SumOfAggLineAmount aggregation
--             before starting the demo
--
EVALUATE
SUMMARIZECOLUMNS (
    'Date'[Year],
    Customer[Continent],
    Customer[Country],
    "Sum of Quantity", SUMX ( Sales, Sales[Quantity] * Sales[Net Price] )
)
