--
--  Database: Contoso 100Mx10 DQ
--  CPU: AMD Ryzen 9 7900X 12-Core Processor 4.70 GHz
--
--  Execute this query in a model with the aggregation 
--  AggregatedSales (DirectQuery mode)
--
EVALUATE
SUMMARIZECOLUMNS ( 
    'Date'[Year],
    'Product'[Color],
    Customer[Continent],
    Customer[Country],
    TREATAS ( { "Red", "Blue", "White" }, 'Product'[Color] ),
    "Quantity", SUM ( Sales[Quantity] )
)        
