--
--  Database: Contoso 100Mx10 DQ
--  CPU: AMD Ryzen 9 7900X 12-Core Processor 4.70 GHz
--
--  Query executed on the remote model (3rd DAX SE query in local model)
--
DEFINE
    VAR _Var0 = { 2020 }
EVALUATE
GROUPCROSSAPPLYTABLE (
    'Date'[Year],
    TREATAS (
        _Var0,
        'Date'[Year]
    ),
    "L1",
        SUMMARIZE (
            VALUES ( 'Date' ),
            'Date'[Month Number]
        )
)
