--
--  Database: Contoso 100Mx10 DQ
--  CPU: AMD Ryzen 9 7900X 12-Core Processor 4.70 GHz
--

--
--  Query executed on the local model 
--
EVALUATE
SUMMARIZECOLUMNS (
    ROLLUPADDISSUBTOTAL (
        ROLLUPGROUP ( 'Sales Segmented'[Segment], 'Sales Segmented'[MinValue] ),
        "IsGrandTotalRowTotal"
    ),
    "Sales_Amount", 'Sales'[Sales Amount]
)
ORDER BY
    [IsGrandTotalRowTotal] DESC,
    'Sales Segmented'[MinValue],
    'Sales Segmented'[Segment]
