--
--  Database: Contoso 100Mx10 DQ
--  CPU: AMD Ryzen 9 7900X 12-Core Processor 4.70 GHz
--

--
--  Query executed on the local model 
--
--  NOTE: the Budget YTD measure is defined with a DATESYTD 
--        applied to the 'Local Date'[Date] column instead of 
--        'Date'[Date] column. The REMOVEFILTERS ( Date ) is required.
EVALUATE
SUMMARIZECOLUMNS (
    Customer[Country],
    'Date'[Year],
    'Date'[Month Number],
    TREATAS ( { 2020 }, 'Date'[Year] ),
    "Budget YTD",
        CALCULATE (
            [Budget Amount],
            REMOVEFILTERS ( 'Date' ),
            DATESYTD ( 'Local Date'[Date] )
        )
)
ORDER BY
    [Country],
    [Year],
    [Month Number]
