--
--  Database: Contoso 100Mx10 DQ
--  CPU: AMD Ryzen 9 7900X 12-Core Processor 4.70 GHz
--

--
--  Query executed on the local model 
--
EVALUATE
SUMMARIZECOLUMNS (
    Customer[Country],
    'Date'[Year],
    'Date'[Month Number],
    TREATAS ( { 2020 }, 'Date'[Year] ),
    "Budget YTD",
        CALCULATE (
            [Budget Amount],
            DATESYTD ( 'Date'[Date] )
        )
)
ORDER BY
    [Country],
    [Year],
    [Month Number]
