--
--  Database: Contoso 100M
--  CPU: AMD Ryzen Threadripper 3970X 32-Core Processor 3.72 GHz
--
-- Create calculated table
Security = 
    VAR CountriesAndBrands = 
        SUMMARIZE ( Sales, Customer[Country], 'Product'[Brand] )
    VAR Result = 
        ADDCOLUMNS ( 
            CountriesAndBrands,
            "SecurityKey", ROWNUMBER ( CountriesAndBrands )
        )
    RETURN
        Result 
