--
--  Database: Contoso 100M
--  CPU: AMD Ryzen Threadripper 3970X 32-Core Processor 3.72 GHz
--

-- Create ComplexRuleDynamicOptimized security role
-- Apply the following filter to Security table
( Security[Country], Security[Brand] ) 
    IN SELECTCOLUMNS ( 
        FILTER ( 
            UserCountriesBrands,
            UserCountriesBrands[UserName] == USERNAME ()
        ),
        [Country],
        [Brand]
    )
