--
--  Database: Contoso 100M
--  CPU: AMD Ryzen Threadripper 3970X 32-Core Processor 3.72 GHz
--
-- Create calculated column in Sales table
SecurityKey =
    LOOKUPVALUE (
        Security[SecurityKey],
        Security[Brand], RELATED ( 'Product'[Brand] ),
        Security[Country], RELATED ( Customer[Country] )
    ) 
