--
--  Database: Contoso 100M
--  CPU: AMD Ryzen Threadripper 3970X 32-Core Processor 3.72 GHz
--
-- Create calculated table
UserContinents = 
    SELECTCOLUMNS (
        {
            ( "marco@contoso.com", "Europe" ),
            ( "marco@contoso.com", "North America" ),
            ( "alberto@contoso.com", "North America" ),
            ( "alberto@contoso.com", "Australia" )
        },
        "UserName", [Value1],
        "Continent", [Value2]
    )
