--
--  Database: Contoso 100M.PBIX
--  CPU:      AMD Ryzen Threadripper 3970X 32-Core Processor 3.72 GHz
--
EVALUATE
SUMMARIZECOLUMNS (
    ROLLUPADDISSUBTOTAL ( 'Product'[Brand], "BrandSubtotal" ),
    TREATAS ( { "Red" }, Product[Color] ),
    "# Products",
        DISTINCTCOUNT ( Sales[ProductKey] )
)
ORDER BY Product[Brand]
