--
--  Database: Contoso 100M
--  CPU:      AMD Ryzen Threadripper 3970X 32-Core Processor 3.72 GHz
--
EVALUATE
SUMMARIZECOLUMNS (
    'Product'[Brand],
    "Test",
        DIVIDE ( 
            CALCULATE (
                [Sales Amount],
                'Product'[Color] = "Blue",
                'Product'[Category] = "Audio"

            ),
            CALCULATE (
                [Total Cost],
                'Product'[Color] = "Red",
                'Product'[Category] = "Audio"

            )
        )
)
