--
--  Database: Contoso 100M.PBIX
--  CPU:      AMD Ryzen Threadripper 3970X 32-Core Processor 3.72 GHz
--
DEFINE
    MEASURE Sales[Big Sales Amount (slow)] =
        CALCULATE (
            [Sales Amount],
            KEEPFILTERS ( Sales[Quantity] * Sales[Net Price] > 1000 )
        )

EVALUATE
SUMMARIZECOLUMNS (
    'Product'[Brand], 
    "Big_Sales_Amount", 'Sales'[Big Sales Amount (slow)]
)
