--
--  Database: Contoso 10K
--  CPU:      AMD Ryzen Threadripper 3970X 32-Core Processor 3.72 GHz
--
EVALUATE
SUMMARIZECOLUMNS (
    'Product DQ'[Brand],
    "# Transactions",
        SUMX ( 
            'Sales DQ',
            BITRSHIFT ( 'Sales DQ'[Quantity], 2 )
        )
)
