--
--  Database: Contoso 100M
--  CPU:      AMD Ryzen Threadripper 3970X 32-Core Processor 3.72 GHz
--
EVALUATE
SUMMARIZECOLUMNS (
    Product[Brand],
    "Sales", [Sales Amount],
    "Sales > 1",
        SUMX (
            Sales,
            IF (
                Sales[Quantity] > 1,
                Sales[Quantity] * Sales[Net Price]
            )
        )
)



