--
--  Database: Contoso 100M
--  CPU:      AMD Ryzen Threadripper 3970X 32-Core Processor 3.72 GHz
--
EVALUATE
SUMMARIZECOLUMNS (
    'Date'[Date],
    'Product'[Color],
    "Sales YTD",
        CALCULATE (
            [Sales Amount],
            DATESYTD ( 'Date'[Date] )
        )
)

