--
--  Database: Contoso 10K
--  CPU:      AMD Ryzen Threadripper 3970X 32-Core Processor 3.72 GHz
--
EVALUATE
SUMMARIZECOLUMNS (
    'Product DQ'[Brand],
    "Quantity GT 1",
        SUMX ( 
            'Sales DQ',
            IF ( 'Sales DQ'[Quantity] > 1, 'Sales DQ'[Quantity] )
        )
)
