--
--  Database: Contoso 100M
--  CPU:      AMD Ryzen Threadripper 3970X 32-Core Processor 3.72 GHz
--
EVALUATE
SUMMARIZECOLUMNS (
    Product[Brand],
    "Sales", [Sales Amount],
    "Margin", [Margin],
    "Sales > 1",
        CALCULATE (
            [Sales Amount],
            Sales[Quantity] > 1
        )
)




