--
--  Database: Contoso 100Mx10 DQ
--  CPU:      AMD Ryzen Threadripper 3970X 32-Core Processor 3.72 GHz
--
EVALUATE
SUMMARIZECOLUMNS (
    'Product'[Product Name],
    "Last price",
        VAR ProdsAndDates =
            TREATAS (
                ADDCOLUMNS (
                    ALLSELECTED ( 'Product'[Product Name] ),
                    "@LastDate", CALCULATE ( MAX ( Sales[Order Date] ) )
                ),
                'Product'[Product Name],
                Sales[Order Date]
            )
        VAR Result =
            CALCULATE ( AVERAGE ( Sales[Net Price] ), KEEPFILTERS ( ProdsAndDates ) )
        RETURN
            Result
)
ORDER BY 'Product'[Product Name]

