--
--  Database: Contoso 100Mx10 DQ
--  CPU: AMD Ryzen 9 7900X 12-Core Processor 4.70 GHz
--
DEFINE
    MEASURE Sales[Sales PY] =
        VAR LastDay = MAX ( 'Date'[Date] )
        VAR EndSPLY = EOMONTH ( LastDay, -12 )
        VAR StartSPLY = EOMONTH ( LastDay, -13 ) + 1
        RETURN
            CALCULATE ( [Sales Amount], DATESBETWEEN ( 'Date'[Date], StartSPLY, EndSPLY ) )

EVALUATE
SUMMARIZECOLUMNS (
    'Date'[Year Month],
    'Date'[Year Month Number],
    "Sales Growth %", DIVIDE ( [Sales Amount] - [Sales PY], [Sales PY] )
)
ORDER BY 'Date'[Year Month Number]

