--
--  Database: Contoso 100Mx10 DQ
--  CPU: AMD Ryzen 9 7900X 12-Core Processor 4.70 GHz
--
EVALUATE
SUMMARIZECOLUMNS (
    'Date'[Year Month Number],
    TREATAS ( { 2010 }, 'Date'[Year] ),
    "# Products",
        CALCULATE (
            DISTINCTCOUNTNOBLANK ( Sales[ProductKey] ),
            DATESYTD ( 'Date'[Date] )
        )
)