--
--  Database: Contoso 100Mx10 DQ
--  CPU:      AMD Ryzen Threadripper 3970X 32-Core Processor 3.72 GHz
--
EVALUATE
SUMMARIZECOLUMNS (
    'Product'[Product Name],
    "Last price",
        CALCULATE (
            AVERAGE ( Sales[Net Price] ),
            LASTDATE ( Sales[Order Date] )
        )
)
ORDER BY 'Product'[Product Name]
