--
--  Database: Contoso 100Mx10 DQ
--  CPU: AMD Ryzen 9 7900X 12-Core Processor 4.70 GHz
--
DEFINE
    MEASURE Sales[Sales PY] =
        VAR CurrentMonth =
            MAX ( 'Date'[Year Month Number] )
        RETURN
            CALCULATE (
                [Sales Amount],
                REMOVEFILTERS ( 'Date' ),
                'Date'[Year Month Number] = CurrentMonth - 12
            )

EVALUATE
SUMMARIZECOLUMNS (
    'Date'[Year Month],
    'Date'[Year Month Number],
    "Sales Growth %", DIVIDE ( [Sales Amount] - [Sales PY], [Sales PY] )
)
ORDER BY 'Date'[Year Month Number]
